# Generated by Django 5.0.1 on 2025-12-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('EXERCISE', 'Exercise'), ('READING', 'Reading'), ('LISTENING', 'Listening')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=15)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILL_BLANK', 'Fill in the Blank'), ('TRANSLATION', 'Translation'), ('MATCHING', 'Matching')], max_length=20)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('example_sentence_de', models.TextField()),
                ('example_sentence_en', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='lessons.lesson')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary',
                'db_table': 'vocabulary',
            },
        ),
    ]
